language: go
go: 1.4
sudo: false

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get golang.org/x/lint/golint
  - go get golang.org/x/crypto/bcrypt

  - go get github.com/stretchr/testify

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci github.com/steenzout/go-playground/unix
  - go test -cover ./...
  - golint ./...

